[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.0.1"
dependencies = []

[project.optional-dependencies]
test = [
    "pyspark == 3.3.1",
]
build = [
    "setuptools == 67.4.0",
    "build == 0.10.0"
]
